
NDefines.NGraphics.MINIMUM_PROVINCE_SIZE_IN_PIXELS = 1

NDefines.NDiplomacy.TENSION_STATE_VALUE = 1.5
NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 1.5	-- Amount of tension generated by annexing a state you don't have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CLAIM = 0.5	-- Amount of tension generated by annexing a state you DO have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0.3	-- Amount of tension generated by annexing a state that is your core